version: "3"

services:
  web:
    container_name: ride_backend
    build: .
    depends_on:
      - mongo
    volumes:
      - ./:/usr/src/app
    command: npm run start:debug
    ports:
      - 4000:3000
      - 9229:9229
  mongo:
    container_name: ride_mongo
    image: mongo:5
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 9876
    volumes:
      - ride-mongo-volume:/data/db
volumes:
  ride-mongo-volume:
